[tool.poetry]
name = "constallation-aws"
version = "1.0.0"
description = ""
authors = ["CoulterStutz <coultercash@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

